### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Gr33nbl00d** [lanimall/ehcache-io#2]
Could you specify the license?

**Comment by lanimall** [comment]
Good point I usually put the license but seems like I forgot in this case. I’ll add.

**Comment by michaeljohnalbers** [comment]
Any updates on this? This extension exactly fits a use case I have at work. It would be nice to clarify if we can fork this and update it to work with newer version of ehcache.

**Comment by fabien-sanglier-ibm** [comment]
hey thanks for following up on this...I haven't really touched this project in a while, but now added the license (apache 2.0)...
Feel free to fork and update. Let me know if any question.
